oneconcern/datamon

.circleci/config.yml
cmd/datamon/cmd/bundle_mutable_mount.go
cmd/datamon/cmd/cli_fuse_test.go
cmd/datamon/cmd/cli_test.go

toward #132 , this diff runs datamon as a separate process in order to test FUSE functionality

mutable fs to CLI, init FUSE tests

---

pkg/ritesh-test-bundles/1H66t9KJzUEyUb85nLsbUTIJTED/bundle.json

Remove unwanted test data

---

pkg/core/bundle_pack.go

CLI bundle upload concurrency patterns

---

pkg/storage/gcs/store.go
pkg/storage/gcs/store_test.go

Allow range reads in the Store implementation for GCS.

GCS implemented range reads.

---

pkg/core/bundle_pack.go

Reverts oneconcern/datamon#167

Revert "CLI bundle upload concurrency patterns"

---

pkg/core/fs_integration_test.go
pkg/core/repo_list.go
pkg/model/bundle.go

metadata store keys api boundary to model pkg

---

Makefile
sidecar.Dockerfile

this adds a build target to produce sidecar images for distribution

init sidecar Docker build

---

hack/fuse-demo/sidecar.Dockerfile
pkg/core/fs.go
pkg/core/fs_ro_ops.go

Mount the FS as non root in the sidecar demo
Set root permission to 0777

Allow for root to be readable by all.

---

cmd/datamon/cmd/bundle.go
cmd/datamon/cmd/bundle_mount.go
cmd/datamon/cmd/root.go
go.mod
pkg/cafs/cafs.go
pkg/cafs/reader.go
pkg/cafs/reader_test.go
pkg/cafs/writer.go
pkg/core/bundle.go
pkg/core/bundle_read.go
pkg/core/fs_ro_ops.go
pkg/storage/gcs/store.go
pkg/storage/localfs/store.go
pkg/storage/multi.go
pkg/storage/store.go

This supersedes https://github.com/oneconcern/datamon/pull/177
Includes 
1. Caching of working set of Blobs
2. Fixes for passing CI.

CAFS streaming

---

cmd/datamon/cmd/bundle.go
cmd/datamon/cmd/bundle_download.go
cmd/datamon/cmd/bundle_download_file.go
cmd/datamon/cmd/bundle_list_file.go
cmd/datamon/cmd/bundle_mount.go
cmd/datamon/cmd/bundle_upload.go
cmd/datamon/cmd/cli_test.go
cmd/datamon/cmd/label.go
cmd/datamon/cmd/label_list.go
cmd/datamon/cmd/label_set.go
cmd/datamon/cmd/root.go
pkg/core/bundle.go
pkg/core/label.go
pkg/core/label_list.go
pkg/model/bundle.go
pkg/model/label.go

initialize labels implementation

---

cmd/datamon/cmd/bundle_download.go
cmd/datamon/cmd/bundle_mount.go
cmd/datamon/cmd/cli_fuse_test.go
cmd/datamon/cmd/cli_test.go
cmd/datamon/cmd/fsops.go

Create directories pass into CLI.

---

README.md
cmd/datamon/cmd/label_list.go

documentation updates corresponding to #87

document labels feature

---

Makefile
binaries.Dockerfile
go.sum
hack/release_from_docker_build.sh

binary builds

---

go.sum
pkg/cafs/cafs.go
pkg/core/bundle.go
pkg/core/label.go

Go modules update and minor fixes

---

cmd/datamon/cmd/web.go
go.mod
go.sum
pkg/web/public/assets/css/vendor/normalize_8.0.1.css
pkg/web/reverse/reverse.go
pkg/web/routes.go
pkg/web/tmpl/drivers/bundle__list_files.html
pkg/web/tmpl/drivers/home.html
pkg/web/tmpl/drivers/repo__list_bundles.html
pkg/web/tmpl/helpers/base.html

init webserver

---

pkg/cafs/reader.go

Fix the error handling to fail gracefully on backend errors.

Fix error handling on concurrent read backend failure.

---

pkg/cafs/reader.go

Fix the channel creation and when the channel is written to.

Reduce concurrent on reads

---

cmd/datamon/cmd/bundle_download.go
cmd/datamon/cmd/bundle_upload.go
cmd/datamon/cmd/cli_test.go
cmd/datamon/cmd/flags.go
pkg/cafs/cafs.go
pkg/cafs/reader.go
pkg/core/bundle.go
pkg/core/bundle_unpack.go
pkg/storage/localfs/store.go

this is to address the [latest requirements](https://github.com/oneconcern/datamon/issues/171#issuecomment-503753719) on #171 , namely

generic concurrency-factor flag on upload, download

---

pkg/cafs/cafs.go
pkg/cafs/freelists.go
pkg/cafs/reader.go

extract buffer pool implementation from #227 to address [1] on #226

buffer pool cafs reader ReadAt

---

Makefile
hack/fuse-demo/create_ro_pod.sh
hack/fuse-demo/follow_logs.sh
hack/fuse-demo/run_shell.sh
hack/fuse-demo/shell.Dockerfile
hack/fuse-demo/sidecar.Dockerfile
hack/k8s/example-ro.template.yaml
internal/prof.go

another #227 extraction:  the modifications to the FUSE RO demo to allow ad-hoc benchmarking with `htop` and misc functions in go's runtime.  the changes here are the suggested methodology for validating the efficacy of all changes toward #226 (#229 and future).

ro fuse fs memory benchmarking setup

---

.circleci/config.yml
cmd/datamon/cmd/cli_test.go
cmd/datamon/cmd/label.go
cmd/datamon/cmd/label_get.go
cmd/datamon/cmd/label_list.go
cmd/datamon/cmd/root.go
go.mod
hack/fuse-demo/wrap_datamon.sh
pkg/core/bundle.go
pkg/core/label.go
pkg/storage/gcs/store.go

implement `label get` per #231

init label get cmd

---

go.mod
go.sum
pkg/core/bundle.go
pkg/core/bundle_unpack.go

towards iss #152 regarding concurrency patterns, also clearing the ground a bit for `bundle update` in #214

download cleanup, concurrency patterns and otherwise

---

pkg/core/bundle_pack.go
pkg/core/bundle_unpack.go

this diff removes the `doneC` from the implementations of `bundle upload` and `download`.
the purpose of this channel is to broadcast errors from the "main thread" to all goroutines such that channel operations expecting to sync with the main thread do not park indefinitely in the case of an error with the net result of goroutine leaks.
meanwhile, in the case of many goroutines being run at once, it's been observed that, without the `doneC`, uploads and downloads don't work.  we could speculate that the desired non-blocking behavior in the case of errors is occurring when there are not errors.
in any case, since the overall binary typically exits on the sort of error conditions that the `doneC` is used to signal, leaks are secondary to the issue #239 of correctness at scale:  we needn't …

remove error signal channel from upload and download implementations

---

.circleci/config.yml
README.md
deploy/datamon.sh

debug `deploy/datamon.sh` and update the readme.

debug desktop install shell script

---

pkg/core/bundle_pack.go

with this diff, filelist metadata is written during file uploads rather than buffering the data in memory and uploading filelists after all uploads are complete.
as a result, there is not unbounded memory usage according to the number of files being uploaded.  the disadvantage is that that some stray filelist metadata might get written in case of a bundle upload that fails midway through.  of course, this latter case was still possible even when filelists were written after all.

incremental filelist writes

---

hack/fuse-demo/follow_coord_logs.sh
hack/fuse-demo/run_coord_shell.sh
hack/fuse-demo/verify_coord_bundle.sh
hack/fuse-demo/wrap_application.sh
hack/fuse-demo/wrap_datamon.sh
hack/k8s/example-coord.template.yaml

this is preparation of the branch in #245 for merge into what will eventually be a versioned release.  i'm leaving #245 in place to track the image built for https://github.com/oneconcern/seismic_ml/pull/269
----
~~additionally, while preparing this merge request, we'd like to try out (and document as necessary) the means of using the `fuse-ro-demo` and/or `fuse-demo-coord` (Makefile targets) on the Docker for Desktop kubernetes cluster.~~

sidecar bundle id param

---

pkg/model/bundle.go
pkg/model/bundle_test.go

debug model.GetArchivePathComponents

---

cmd/datamon/cmd/bundle_download.go
cmd/datamon/cmd/bundle_download_file.go
cmd/datamon/cmd/bundle_mount.go
cmd/datamon/cmd/bundle_update.go
cmd/datamon/cmd/cli_test.go
cmd/datamon/cmd/flags.go
go.mod
go.sum
pkg/core/bundle.go
pkg/core/bundle_unpack.go
pkg/model/bundle.go

the `bundle update` part of #214

init bundle update

---

pkg/core/fs_ro_ops.go

this stylistic cleanup decomposes `populateFS`, the function that prepares in-memory data structures for the read-only filesystem, into several functions for clarity.  it was written a while ago while work to reduce the memory usage of the read-only filesystem was in progress, and although no changes are here included to that end, the stylistic cleanup is now for review toward maintainability.

populateFS aesthetics

---

pkg/storage/gcs/store_test.go

This is in preparation for WAL and related changes coming to the GCS
store abstraction.
Clean up the testing code in place.

Clean up GCS tests.

---

cmd/datamon/cmd/bundle.go
cmd/datamon/cmd/bundle_get.go
cmd/datamon/cmd/bundle_list.go
cmd/datamon/cmd/cli_test.go
cmd/datamon/cmd/repo.go
cmd/datamon/cmd/repo_get.go
cmd/datamon/cmd/repo_list.go
pkg/core/bundle.go
pkg/core/bundle_unpack.go
pkg/core/repo_list.go

repo|bundle get

---

.golangci.yml
cmd/backup2blobs/cmd/actOnFilelist.go
cmd/datamon/cmd/bundle.go
cmd/datamon/cmd/bundle_diff.go
cmd/datamon/cmd/bundle_download.go
cmd/datamon/cmd/bundle_get.go
cmd/datamon/cmd/bundle_list.go
cmd/datamon/cmd/bundle_list_file.go
cmd/datamon/cmd/bundle_mount.go
cmd/datamon/cmd/bundle_mutable_mount.go
cmd/datamon/cmd/bundle_update.go
cmd/datamon/cmd/bundle_upload.go
cmd/datamon/cmd/cli_fuse_test.go
cmd/datamon/cmd/cli_test.go
cmd/datamon/cmd/completion.go
cmd/datamon/cmd/config.go
cmd/datamon/cmd/flags.go
cmd/datamon/cmd/fsops.go
cmd/datamon/cmd/root.go
cmd/datamon/cmd/sig_handlers.go
cmd/datamon/cmd/web.go
cmd/metrics/cmd/flags.go
cmd/metrics/cmd/rand_gen_store.go
cmd/metrics/cmd/root.go
pkg/core/bundle_read.go
pkg/core/repo_list.go
pkg/csi/node.go
pkg/storage/gcs/store_test.go
pkg/web/reverse/reverse.go

* moved linting rules settings from CI config to .golangci.yml
* applied a few linting
* revisited error reporting

Linting & errors reporting

---

pkg/sidecar/param/pub_api.go
pkg/sidecar/param/pub_api_test.go

this is a draft of the golang api portion of #270 ..
.. yaml deserialization is via public types and the yaml lib.
environment variable deserialization not (yet) added..

draft golang sidecar parameterization api

---

cmd/datamon/cmd/root.go
pkg/auth/google/auth.go
pkg/core/label_list.go
pkg/model/label.go

these are a few items i wasn't able to collaborate on, being away from the kinesis "freestyle 2" :/  keyboard, last week.
low priority in terms of sprint goals.

unreviewed review

---

cmd/datamon/cmd/label_list.go
pkg/core/label_list_test.go

The remaining part of #288, since this has been merged before I had a change to push my local changes.

added parallel tuning flags to label list cmd

---

hack/fuse-demo/wrap_application.sh
hack/fuse-demo/wrap_datamon.sh

This is in preparation for cutting a release.

Minor fixes to improve usability.

---

cmd/datamon/cmd/bundle_list.go
cmd/datamon/cmd/label_list.go
cmd/datamon/cmd/repo_list.go

Tune concurrency params

---

hack/fuse-demo/wrap_datamon.sh

To print the bundle id at the end log stderr as well.

Log wrap datamon script output for stderr

---

pkg/core/fs_ro_ops.go

Reduce logging verbosity for read only fuse

---

.golangci.yml
pkg/core/bundle_list.go
pkg/core/keys.go
pkg/core/label_list.go
pkg/core/repo_list.go

refactor(core): removed obsolete ListReposPaginated func (used only with CSI)

refactor(core): removed unnessary param from keys fetcher

---

.golangci.yml
README.md
docs/context.md
docs/datamover.md
docs/design.md
docs/features.md
docs/install.md
docs/kubernetes.md
docs/sidecar.md
docs/usage.md
docs/wal.md

doc refactoring

---

docs/sidecar.md

doc(sidecar): more doc on sidecar

---

.circleci/config.yml
Dockerfile
Makefile
binaries.Dockerfile
datamover.Dockerfile
hack/fuse-demo/demo_pg_coord.sh
migrate.Dockerfile
sidecar-pg.Dockerfile
sidecar.Dockerfile

refactored Makefile and CI workflows

---

README.md
docs/concepts.md
docs/usage.md

augmented usage.md doc

---

cmd/datamon/cmd/context.go
cmd/datamon/cmd/context_get.go
go.sum
pkg/context/context.go

implement `context get` similar to that of bundles and repos in order to implement fail-fast on non-exist context when plumbing parameter thru sidecar in #306

context get

---

.circleci/config.yml
binaries.Dockerfile
hack/fuse-demo/create_coord_pod.sh
hack/fuse-demo/demo_coord.sh
hack/fuse-demo/verify_coord_bundle.sh
hack/fuse-demo/wrap_datamon.sh
hack/k8s/example-coord.template.yaml

#305 and #310 together with
* plumbing to connect context bucket and context name to yaml
* demo/test script ported to ci

fuse sidecar context parameterization

---

Makefile

fix(build): makefile to prepare for local targets output

---

pkg/model/bundle.go
pkg/model/paths.go

Follow up on review comments on  #326 

chore(model): fixed nitpick on constant name

---

docs/concepts.md
pkg/auth/google/doc.go
pkg/auth/status/status.go
pkg/cafs/doc.go
pkg/config/processor.go
pkg/convert/doc.go
pkg/core/status/status.go
pkg/dlogger/logger.go
pkg/model/bundle.go
pkg/model/context.go
pkg/model/doc.go
pkg/storage/doc.go
pkg/storage/gcs/store.go
pkg/storage/localfs/store.go
pkg/storage/status/status.go
pkg/storage/sthree/store.go
pkg/storage/store.go
pkg/wal/wal.go
pkg/web/routes.go

doc: tidy up a little our generated godoc

---

pkg/errors/errors.go
pkg/wal/status/status.go
pkg/wal/wal.go
pkg/wal/wal_test.go

Trying to get to neater logging w/ errors.
TODO: I'd like to wrap zap.Field enrichments in the error just as well, but this is not so easy...

refactor wal, using a combination WrapWithLog and status

---

.goreleaser.yml

Skip UPX to fix mac build

---

cmd/datamon/cmd/cli_test.go

in response to [a slack message](https://oneconcern.slack.com/archives/CCMQ25SP5/p1576793373006500), this patch uses the datamon storage apis to delete gcs buckets in the cli tests rather than directly using the google cloud go apis.
this is consistent with the wal tests.
----
note that `datamon-deleteme-*` buckets can still appear if, for instance, a cli test is interrupted during a local run.
as added insurance, i could try adding a signal handler to the tests to delete buckets in such an event.  it's unclear to me whether the time savings due to automation or the time it takes to delete buckets using the gcs web "console" are greater in this case.

cli tests delete objects using storage apis

---

pkg/core/bundle.go

Include the name filter

---

cmd/datamon/cmd/bundle_list_file.go
cmd/datamon/cmd/cli_test.go
cmd/datamon/cmd/fatal.go

Log bundle file list to std out

---

cmd/datamon/cmd/config_set.go
docs/usage/datamon_config.md
docs/usage/datamon_config_set.md

Alias create to set to avoid breakage.

Rename create config to config set.

---

.circleci/config.yml

fix(ci): more verbose CI unit testing displayed on console

---

cmd/datamon/cmd/web.go

Fix Web command

---

pkg/core/fs_rw_ops.go

fix(core): less verbose fuse rw operations

---

cmd/datamon/cmd/config_set.go
docs/usage/datamon_bundle_mount_new.md
docs/usage/datamon_config_set.md

fix(doc): added CLI example to switch context using datamon config set --context xxx

---

.circleci/config.yml
pkg/core/bundle_test.go
pkg/core/fs.go
pkg/core/fs_common.go
pkg/core/fs_integration_test.go
pkg/core/fs_ro_ops.go
pkg/core/fs_ro_ops_test.go
pkg/core/fs_rw_ops.go
pkg/core/fs_test.go

* refactored bundle unit tests
* refactored fuse mount unit tests, with more test scenarios
* fixes #332
* fixes map concurrency issues in fuse RW mount
* configured a parallel job on circleCI VM to run integration test with fuse (introduced some throttling to avoid hangs, which I could not reproduce otherwise)

chore(core): more unit testing of the fuse mount core capabilities

---

.goreleaser.yml

Rename the binary artifact to enable co-existence with v1 datamon binary.

Rename datamon v2 to datamon2

---

cmd/datamon/cmd/self_upgrade.go
cmd/datamon/cmd/self_upgrade_test.go

adapted self-upgrade test to new binary datamon2

---

hack/fuse-demo/wrap_application.sh
hack/fuse-demo/wrap_datamon.sh

there are a few error messages or parts of error messages that the sidecar was printing to the wrong output stream that this patch corrects

minor sidecar stdio fixes

---

cmd/datamon/cmd/bundle_get.go
cmd/datamon/cmd/context_get.go
cmd/datamon/cmd/fatal.go
cmd/datamon/cmd/label_get.go
cmd/datamon/cmd/repo_get.go

Ref: https://app.circleci.com/jobs/github/oneconcern/datamon/4037

Address linting errors

---

cmd/datamon/cmd/cli_test.go
pkg/core/bundle_unpack.go

add tests for `--files` flag on `bundle upload` and the `--name-filter` flag on `bundle download`

test upload and download subsetting flags

---

cmd/datamon/cmd/bundle.go
cmd/datamon/cmd/bundle_diff.go
cmd/datamon/cmd/bundle_get.go
cmd/datamon/cmd/bundle_list.go
cmd/datamon/cmd/bundle_list_file.go
cmd/datamon/cmd/bundle_mutable_mount.go
cmd/datamon/cmd/bundle_upload.go
cmd/datamon/cmd/cli_test.go
cmd/datamon/cmd/config_set.go
cmd/datamon/cmd/context_get.go
cmd/datamon/cmd/context_list.go
cmd/datamon/cmd/fatal.go
cmd/datamon/cmd/flags.go
cmd/datamon/cmd/fsops.go
cmd/datamon/cmd/label_get.go
cmd/datamon/cmd/label_list.go
cmd/datamon/cmd/mocks_test.go
cmd/datamon/cmd/repo_get.go
cmd/datamon/cmd/repo_list.go
cmd/datamon/cmd/root.go
cmd/datamon/cmd/self_upgrade.go
cmd/datamon/cmd/usage.go
cmd/datamon/cmd/version.go
hack/fuse-demo/create_ro_pod.sh
hack/fuse-demo/verify_coord_bundle.sh

A little code is sometimes better than a long discussion... My personal take on #375 is this.

CLI output to stdout, errs and zap to stderr (my take on #375)

---

.golangci.yml
pkg/core/bundle.go

Signed-off-by: Ransom Williams <rwilliams@oneconcern.com>

[v1] fix download name filter

---

cmd/datamon/cmd/flags.go

@fredbi the SDK searches in more places than the logic you put in there. If nothing else let SDK try.

Always let SDK try to get principal

---

cmd/datamon/cmd/flags.go
cmd/datamon/cmd/label_set.go

Clean up label set error on bundle not found

---

cmd/datamon/cmd/self_upgrade_test.go

Signed-off-by: Ransom Williams <rwilliams@oneconcern.com>

CI test pass (TestSelfUpgrade regexp) 

---

sidecar.Dockerfile

fixed broken sidecar image build

---

pkg/core/bundle_list.go

* shortened error handling, relocalized unmarshalling and remain consistent with how other objects are listed

refact(core): small refactoring of the bundle split list

---

.circleci/config.yml
hack/fuse-demo/follow_logs.sh
hack/go-generate.sh
hack/releaser/post-build.sh
k8s/migratev2/scripts/funcs.sh
k8s/migratev2/scripts/migrate-history.sh
k8s/migratev2/scripts/migrate-repos.sh
k8s/migratev2/scripts/migrate.sh
pkg/fuse/fs.go
pkg/fuse/fs_rw_ops.go
pkg/model/bundle.go
pkg/model/context.go

Following a remark from @ransomw1c, ensure shell linting on all scripts (fixed linting issues in k8s migration scripts)

Chore ensure shell linting

---

pkg/model/bundle.go
pkg/model/diamond.go
pkg/model/diamond_options.go
pkg/model/diamond_test.go
pkg/model/doc.go
pkg/model/paths.go
pkg/model/paths_test.go
pkg/model/version.go

~~design doc in this branch is not up-to-date: please ignore that one.~~

Diamonds #2: Diamond metadata  models and paths

---

pkg/core/bundle_pack.go
pkg/core/bundle_preserve_disable.go
pkg/core/bundle_preserve_enable.go
pkg/core/bundle_unpack.go
pkg/core/diamond.go
pkg/core/diamond_commit.go
pkg/core/diamond_list.go
pkg/core/diamond_ops.go
pkg/core/diamond_ops_test.go
pkg/core/diamond_options.go
pkg/core/diamond_test.go
pkg/core/index.go
pkg/core/index_iterators.go
pkg/core/index_iterators_test.go
pkg/core/index_options.go
pkg/core/keys.go
pkg/core/keys_test.go
pkg/core/meta_object.go
pkg/core/mocks/bundle_test_utils.go
pkg/core/repo_validate.go
pkg/core/split.go
pkg/core/split_list.go
pkg/core/split_ops.go
pkg/core/split_ops_test.go
pkg/core/split_options.go
pkg/core/status/status.go

~~Still very much WIP.
Those interested may take a look out of curiosity.~~
Feature complete, ready for review
NOTE to reviewers:  this PR gets on board the content of PRs Diamond #1, #2 and #3. 
You might want to focus here on the content of `pkg/core`, other locations being separated in the other PRs.

Diamonds #4: implemented core operations for diamonds and splits - READY

---

cmd/datamon/cmd/cli_fuse_test.go
cmd/datamon/cmd/cli_test.go
cmd/datamon/cmd/diamond.go
cmd/datamon/cmd/diamond_cancel.go
cmd/datamon/cmd/diamond_commit.go
cmd/datamon/cmd/diamond_get.go
cmd/datamon/cmd/diamond_initialize.go
cmd/datamon/cmd/diamond_list.go
cmd/datamon/cmd/diamond_test.go
cmd/datamon/cmd/flags.go
cmd/datamon/cmd/mocks_test.go
cmd/datamon/cmd/split.go
cmd/datamon/cmd/split_add.go
cmd/datamon/cmd/split_get.go
cmd/datamon/cmd/split_list.go
docs/usage/datamon.md
docs/usage/datamon_diamond.md
docs/usage/datamon_diamond_cancel.md
docs/usage/datamon_diamond_commit.md
docs/usage/datamon_diamond_get.md
docs/usage/datamon_diamond_initialize.md
docs/usage/datamon_diamond_list.md
docs/usage/datamon_diamond_split.md
docs/usage/datamon_diamond_split_add.md
docs/usage/datamon_diamond_split_get.md
docs/usage/datamon_diamond_split_list.md

This PR integrates all the work from diamond PRs #1, #2, #3, and #4 
You might want to view the last commits only, starting at https://github.com/oneconcern/datamon/pull/405/commits/1762acf5213b9ae3cb3402dd1124e4dbf608c36d

Diamond #5: CLI - READY

---

pkg/core/diamond.go
pkg/core/diamond_commit.go
pkg/core/split.go

fix(diamond): addressed minor remarks after #403

---

.circleci/config.yml
Makefile
dockerfiles/README.md
docs/install.md

* fixes #431
NOTE to reviewers: please jump at commit https://github.com/oneconcern/datamon/pull/435/commits/ecef099224dc5c18f92176618166ddb88f7850b8 to see changes relative to #428 and friends which this PR is based upon

Doc dockerfiles

---

.circleci/config.yml
Makefile
hack/fuse-demo/create_coord_pg_pod.sh
hack/fuse-demo/create_coord_pod.sh
hack/fuse-demo/demo_coord.sh
hack/fuse-demo/demo_pg_coord.sh
hack/fuse-demo/s.sh

The IP whitelisting requirement did bring a lot of unforeseen complexity to our CI.
Here are some additional fixes to address some known failures.

More ipwhitelisting fixes

---

.golangci.yml
Makefile
cmd/datamon/cmd/cli_test.go
cmd/datamon/cmd/repo_delete.go
cmd/datamon/cmd/repo_delete_files.go
docs/usage/datamon_repo_delete.md
docs/usage/datamon_repo_delete_files.md
go.sum
pkg/core/delete.go

added delete repo command

---

pkg/core/delete.go

removed debug code in core/repo_delete

---

cmd/datamon/cmd/bundle_download.go
cmd/datamon/cmd/flags.go
docs/usage/datamon_bundle_download.md

added option to force bundle download to non-empty destination

---

.circleci/config.yml
dockerfiles/builder.Dockerfile

chore(ci): updated gcloud SDK install procedure on debian

---

k8s/migratev2/scripts/migrate.sh

fix(migration): fixed migration script for v2 k8s job

---

k8s/migratev2/scripts/migrate-history.sh
k8s/migratev2/scripts/migrate.sh

chore(shellcheck): fixed some shellcheck linting issues

---

.circleci/config.yml
cmd/datamon/cmd/repo_rename.go
docs/usage/datamon_repo_rename.md
pkg/core/delete.go
pkg/core/rename.go

feat(repo): added repo rename command

---

k8s/migratev2/scripts/migrate.sh

fixup migration script

---

.circleci/config.yml
.golangci.yml
README.md
dockerfiles/README.md
dockerfiles/builder.Dockerfile
dockerfiles/pgsidecar-base.Dockerfile
pkg/cafs/cafs.go
pkg/convert/unsafe.go

enabled test coverage reporting on coveralls

---

.circleci/config.yml

added -coverpkg flag to run test with extended coverage measurement

---

k8s/purge/build-index/values.default.yaml
k8s/purge/delete-unused/Chart.yaml
k8s/purge/delete-unused/templates/_helpers.tpl
k8s/purge/delete-unused/templates/config.yaml
k8s/purge/delete-unused/templates/job.yaml
k8s/purge/delete-unused/templates/staging-claim.yaml
k8s/purge/delete-unused/templates/staging.yaml
k8s/purge/delete-unused/values.default.yaml
pkg/core/purge.go

added delete-unused as a k8s job

---

k8s/purge/build-index/values.default.yaml
k8s/purge/delete-unused/templates/job.yaml
k8s/purge/delete-unused/values.default.yaml
pkg/core/purge.go

fix(purge): ignore errors on corrupted root keys [EO-438]

---

k8s/purge/build-index/values.default.yaml
k8s/purge/delete-unused/values.default.yaml
pkg/core/purge.go

added build index reporting

---

TODO.txt
k8s/purge/build-index/values.default.yaml
k8s/purge/delete-unused/values.default.yaml
pkg/core/purge.go
pkg/core/purge_options.go
pkg/core/purge_test.go
pkg/model/paths.go

purge: added background uploading of index in chunks

---

pkg/core/repo_squash.go

fixed edge case with determining the latest bundle

---

k8s/purge/build-index/values.default.yaml
k8s/purge/delete-unused/values.default.yaml

purge: updated image pulled tag for v2.6.0

---

pkg/core/purge.go
pkg/core/purge_pebble.go

perf: optimizations to the index building process

---

cmd/datamon/cmd/context_squash.go
cmd/datamon/cmd/flags.go
cmd/datamon/cmd/repo_squash.go
cmd/datamon/cmd/repo_squash_test.go
pkg/core/options.go
pkg/core/repo_squash.go

squash: added option to retain n latest versions

---

docs/purge.md
k8s/purge/build-index/values.default.yaml
k8s/purge/delete-unused/values.default.yaml

updated images and doc

---

cmd/datamon/cmd/flags.go
cmd/datamon/cmd/purge_reverse_lookup.go
cmd/datamon/cmd/root.go

purge: added option to restrict index building to 1 metadata context

---

cmd/datamon/cmd/flags.go
cmd/datamon/cmd/purge_reverse_lookup.go
cmd/datamon/cmd/root.go
pkg/core/purge.go
pkg/core/purge_options.go

feat(purge): added chunk start sequence number as flag

---

cmd/datamon/cmd/repo_squash_test.go
pkg/core/delete.go
pkg/core/delete_options.go
pkg/core/repo_squash.go

perf(squash): reordered label delete operations when squashing a repo
