oneconcern/datamon

cmd/datamon/cmd/cli_test.go
pkg/cafs/reader.go
pkg/core/bundle_unpack.go
pkg/core/fs_integration_test.go

For large bundles, datamon will run into ulimit limitations that will
need customers to fiddle with ulimit. Limit the numbe of concurrent
downloads.
Zero size files should be skipped to fix stuck downloads.

Download concurrency control and skip zero size files.

---

Dockerfile
Makefile
cmd/datamon/cmd/bundle_mutable_mount.go
cmd/datamon/cmd/bundle_upload.go
cmd/datamon/cmd/config.go
cmd/datamon/cmd/config_generate.go
cmd/datamon/cmd/repo_create.go
cmd/datamon/cmd/version.go

this request (at least partially) addresses the versioning requirement of #142 by adding a `version` command, as in
```
% make build-datamon
...
% docker run reg.onec.co/datamon:i142-versioncmd--wip 'version'
Version: 0.2.1-60-g26ab977
Build date: Mon, 13 May 2019 23:38:49 UTC
Commit: 26ab9777a0f6f7d382a8607fd0fd9e6f0822e3b8
```
meanwhile
```
cmd/datamon % go build
cmd/datamon % datamon version
Version: dev
Build date:
Commit:
```
that's because the `-X` [linker flag](https://golang.org/cmd/link/) is used to set some string variables at build time.
----
meanwhile, this commit also makes the contributor name and email optional for commands that don't require these parameters (or at least i'm pretty sure i've caught such commands, do check the diff).  so in particular, it's possible to …

init version command

---

.circleci/config.yml
cmd/datamon/cmd/bundle_mount.go
cmd/datamon/cmd/root.go
cmd/datamon/main.go
pkg/core/fs_ro_ops.go
pkg/csi/node.go

after #137 , `golangci-lint` was disabled in `.circleci/config.yml`.  this re-enables [`golangci-lint`](https://github.com/golangci/golangci-lint), the "linters aggregator" -- i.e. a program that runs a variety of static analysis programs -- with [`golint`](https://github.com/golang/lint#purpose) disabled since it
> is not, and will never be, trustworthy enough for its suggestions to be enforced automatically, for example as part of a build process

fine-grain CI static analysis decisions

---

pkg/cafs/cafs.go
pkg/cafs/writer.go
pkg/core/bundle_pack.go

For large file counts or large files, the concurrency needs to be
reduced to keep memory usage in check which is critical for k8s
deployment.

Limit the concurrency during uploads.

---

cmd/datamon/cmd/bundle_upload.go
pkg/core/bundle.go

this is a quick code-design proposal:  the suggestion is to keep the `Upload(context.Context, core.Bundle)` sig as-is, then add additional `Upload*` funcs around `implUpload` as additional parameters are needed.

bundle Upload api tuning

---

cmd/datamon/cmd/bundle_list.go
cmd/datamon/cmd/label_list.go
cmd/datamon/cmd/repo_list.go
pkg/core/bundle_list.go
pkg/core/bundle_pack.go
pkg/core/label.go
pkg/core/label_list.go
pkg/core/repo_list.go
pkg/model/label.go

mentioned in #153 , this is (at least the start of) a quick cleanup of some todos:
several commands are used to display metadata.  this is a cleanup to make the implementation incrementally more maintainable:  the `core/` api returns types rather than strings (this was part of the original todo), and the `datamon/cmd/` implementation uses `text/template` to format the strings (this is my bright idea 😒 ).

'list' commands cleanup

---

cmd/datamon/cmd/config_generate.go

wrt. @galvare2 's observation that permission bits are set for root access only on `.datamon/datamon.yaml` via the `config` command.
with this change, all bits (root, group, user) are set.

config perms

---

pkg/cafs/reader.go
pkg/core/bundle_unpack.go

The bundle download currently can be more aggressive than what the
system can handle.

Reduce concurrency on bundle download path.

---

pkg/cafs/reader.go

this debugs a [lru cache](https://github.com/hashicorp/golang-lru) usage wherein `Contains` and `Get`, while each is thread-safe individually, are not mutually thread safe in that cache eviction can occur between a `Contains` and `Get`. [here](https://github.com/hashicorp/golang-lru/blob/master/simplelru/lru.go#L73) are the reference implementations of each.

lru bug fix

---

cmd/datamon/cmd/bundle_upload.go
cmd/datamon/cmd/cli_test.go
cmd/datamon/cmd/flags.go
pkg/cafs/cafs.go
pkg/cafs/writer.go
pkg/core/bundle.go
pkg/core/bundle_pack.go

towards #171 , this request is about making the number of goroutines (hence the amount of memory used by the program) during upload configurable at runtime rather than statically parameterized.

configurable concurrency/memory bounds

---

cmd/datamon/cmd/bundle_mount.go
cmd/datamon/cmd/bundle_mutable_mount.go
cmd/datamon/cmd/cli_fuse_test.go
cmd/datamon/cmd/cli_fuse_test.sh

following up on a request from @galvare2 , these changes allow omitting the `--destination` on `bundle mount` (and `bundle mount new`).
when omitted, a subpath of system's `/tmp` directory is constructed by golang's `io/ioutil`.

optional --destination param on mount

---

pkg/core/bundle_pack.go

this patch is comparable to diff #167 towards iss #152 regarding concurrency patterns, specifically the preference for using unbuffered channels.
unlike #167 , this implementation additionally allows for limits on concurrency (number of files being uploaded at a time).

unbuffered channels on bundle upload

---

cmd/datamon/cmd/bundle_download.go
cmd/datamon/cmd/bundle_download_file.go
cmd/datamon/cmd/bundle_list.go
cmd/datamon/cmd/bundle_list_file.go
cmd/datamon/cmd/bundle_mount.go
cmd/datamon/cmd/bundle_mutable_mount.go
cmd/datamon/cmd/bundle_upload.go
cmd/datamon/cmd/config_generate.go
cmd/datamon/cmd/flags.go
cmd/datamon/cmd/fsops.go
cmd/datamon/cmd/label_list.go
cmd/datamon/cmd/label_set.go
cmd/datamon/cmd/repo_create.go
cmd/datamon/cmd/repo_list.go
cmd/datamon/cmd/web.go
pkg/core/bundle.go
pkg/core/label.go

nominally toward #165 , this diff deduplicates creation of objects based on parameters in the `Run:` functions of the various `cobra.Command` structs in the `cmd`/CLI package.
this harmonization might in particular have implications for implementing IPC as discussed in [this comment](https://github.com/oneconcern/datamon/issues/214#issuecomment-506448369) on #214 , the `bundle update` iss.

dedupe cmd Run funcs (stores)

---

cmd/datamon/cmd/bundle_download.go
cmd/datamon/cmd/bundle_mount.go
pkg/core/bundle.go
pkg/core/bundle_test.go
pkg/core/bundle_unpack.go
pkg/core/fs_integration_test.go

part of [3] on #226 , originally started as part of #227 , this diff parallelizes the download of filelists, the bulk of a bundle's metadata.  so although it's not strictly part of parallelizing `populateFS` as mentioned in [3], it's within the spirit of what that item is about:  decreasing the time from starting `bundle mount` to the FUSE mount occurring.
it will also speed up `bundle download`  somewhat as well as (wip at time of creating merge request) `bundle update`.

parallelize bundle file list download

---

cmd/backup2blobs/cmd/blob2file.go
cmd/backup2blobs/cmd/file2blobs.go
cmd/csi/cmd/root.go
cmd/datamon/cmd/bundle.go
cmd/datamon/cmd/bundle_download.go
cmd/datamon/cmd/bundle_download_file.go
cmd/datamon/cmd/bundle_list.go
cmd/datamon/cmd/bundle_list_file.go
cmd/datamon/cmd/bundle_mount.go
cmd/datamon/cmd/bundle_mutable_mount.go
cmd/datamon/cmd/bundle_upload.go
cmd/datamon/cmd/cli_test.go
cmd/datamon/cmd/flags.go
cmd/datamon/cmd/label_get.go
cmd/datamon/cmd/label_list.go
cmd/datamon/cmd/label_set.go
cmd/datamon/cmd/repo_create.go
cmd/datamon/cmd/repo_list.go
cmd/metrics/cmd/upload.go
pkg/storage/gcs/store.go
pkg/storage/gcs/store_test.go
pkg/web/routes.go

this diff is started according to the suggestion in #223 , where a very specific change was made to debug the `storage/gcs` package.
overall, it there's some cleanup that can be done throughout `storage/gcs` .. and possibly wherever `cloud.google.com/go/storage` is used.  exact scope tbd, although there's certainly more to this "one idea per commit" than the suggested change in #233 :  `context.TODO()` calls, for instance, are suggestive that the functions in `storage/gcs` can be parameterized.

gcs store use cleanups

---

.circleci/config.yml

quick housekeeping to ensure the metrics binary build remains coherent.
it's grouped with lint because the linter ought already catch any errors that the build would throw, yet just in case and for clarity it's included as a separate item here.

ensure metrics build in CI

---

cmd/datamon/cmd/bundle_upload.go
cmd/metrics/cmd/flags.go
cmd/metrics/cmd/mock_dest_store.go
cmd/metrics/cmd/root.go
cmd/metrics/cmd/upload.go
pkg/core/bundle_pack.go
pkg/dlogger/logger.go

this diff uses a mock destination (blob and metadata) `storage.Store` in `cmd/metrics` in order to debug #239 .
additionally, several debug-level logging statements are added to the bundle upload implementation.

test filelist upload

---

Makefile
README.md
cmd/backup2blobs/cmd/actOnFilelist.go
cmd/backup2blobs/cmd/generateFileList.go
cmd/datamon/cmd/bundle_mount.go
cmd/datamon/cmd/bundle_upload.go
cmd/metrics/cmd/flags.go
cmd/metrics/cmd/upload.go
cmd/metrics/cmd/write_files.go
datamover.Dockerfile
hack/datamover/access_nfs.sh
hack/datamover/create_demo_job.sh
hack/datamover/create_demo_pod.sh
hack/datamover/datamover.sh
hack/datamover/datamover_metrics.sh
hack/datamover/follow_job_logs.sh
hack/datamover/follow_logs.sh
hack/datamover/nfs_lister.sh
hack/datamover/retrieve_job_logs.sh
hack/datamover/run_job_shell.sh
hack/datamover/run_shell.sh
hack/k8s/datamover.template.yaml
hack/k8s/datamover_job.template.yaml
hack/k8s/datamover_nfs_access.template.yaml
hack/k8s/datamover_nfs_lister.template.yaml
pkg/core/bundle_pack.go

as with the [sidecar](pod/datamon-datamover-test-5b87d6d949-8svcr) used in Argo workflows, this is an operationalization of datamon in the sense that it's a use of datamon in order to accomplish a specific task.  in addition to the datamon program itself, an operationalization consists of any necessary auxiliary programs (for example, the `migrate` program used to create and act on lists of files in this case) and a wrapper script (shell scripts here and in the sidecar, although Python or similar could be used as well), all packaged as a Docker image along with sample Kubernetes YAML, and documented such that datamon users get an interface specific to their needs.
the particular use-case here at One Concern that we're currently operationalizing is backing up and cleaning an NFS filestore …

init datamover image and demo yaml

---

hack/release_from_docker_build.sh

this diff contains a couple of changes to make `release_from_docker_build.sh` consistent with internal standards from other scripts:
* `md5`, the OS X builtin is used instead of `md5sum`, the homebrew install
* zsh is used instead of POSIX or bash for those scripts that are part of the datamon internal environment

release_from_docker_build.sh consistency

---

Makefile
hack/fuse-demo/create_coord_pod.sh
hack/fuse-demo/demo_coord.sh
hack/fuse-demo/wrap_datamon.sh
hack/k8s/example-coord.template.yaml
sidecar.Dockerfile

adding `sudo` to the sidecar docker image in order to `chgrp` `/dev/fuse` such that `fusermount` via `jacobsa/go-fuse` can open this kernel device file.
see #247 for attempts at kubernetes-specific approaches that avoid `sudo`.

Docker Desktop sidecar usage

---

.circleci/config.yml
Makefile
binaries.Dockerfile
cmd/datamon/cmd/cli_test.go
cmd/datamon/cmd/flags.go
cmd/datamon/cmd/root.go
datamover.Dockerfile
go.sum
hack/fuse-demo/coord-datamon.Dockerfile
hack/fuse-demo/create_ro_pod.sh
hack/fuse-demo/run_shell.sh
hack/fuse-demo/wrap_datamon.sh
hack/k8s/example-coord.template.yaml
hack/k8s/example-ro.template.yaml
sidecar.Dockerfile

this patch clears the ground a bit for #256 and other datamon kubernetes "batteries":
* all docker images that require building binaries from golang source are based on `binaries.Dockerfile`, and this is the only docker image that includes `go build` steps
* `wrap_datamon.sh` is converted to zsh.  `wrap_application.sh` is still POSIX sh so that it can be run within any application container from a shared volume.  the battery-specific scripts, on the other hand, run within their respective images and can use any interpreter made available within those docker images
* 3dbeae5d introduced a bug wherein it wasn't possible to specify `--destination` on the `bundle mount` command.  this commit both fixes that bug as well as changes the demo to omit the `--destination` flag such that a temporary …

base docker img, wrap_datamon.sh to zsh, dbg dest store parsing

---

Makefile
hack/release_tag.sh

slight automation increment while setting [v0.7](https://github.com/oneconcern/datamon/releases/tag/v0.7)
the additional Makefile target included builds both [the Argo sidecar](https://github.com/oneconcern/datamon#kubernetes-sidecar-guide) and [the NFS datamover](https://github.com/oneconcern/datamon#datamover-container-guide) and deploys to the repo with a release tag.
the release tag is the same as that used by git when `HEAD` is on such a tag.  otherwise, it's `hash-<hash>`, where `<hash>` is the abbreviated hash out of git.

init build-and-push-release-docker-images Makefile target

---

README.md
cmd/datamon/cmd/cli_test.go
cmd/datamon/cmd/config.go
cmd/datamon/cmd/config_generate.go
cmd/datamon/cmd/deprecated.go
cmd/datamon/cmd/flags.go
cmd/datamon/cmd/mocks_test.go
cmd/datamon/cmd/repo_get.go
cmd/datamon/cmd/root.go
pkg/auth/auth.go
pkg/auth/google/auth.go
pkg/auth/google/auth_test.go
pkg/model/bundle.go
pkg/model/contributor.go

google oauth support for CLI
* at this moment, I am just warning CLI user of some deprecated --name/--email args. Please advise if you want to actually desupport those (will this support all use cases? I admit I am a bit lost given the possibility to change build flags etc)
* user name is no guaranteed from google userinf: using my own user for instance, I could see that this is not hydrated in google info. I set up a fall back on email as name, but we might want to make sure that users are better set up in google. Please advise.
* google oauth is an implementation of the new Authable interface, which at this moment, just gains access to the userinfo. We might want to augment that later on and make it a parameter. Now, this primarily serves the purpose of mocking auth for tests.
* I've …

feat(authentication): first stab at supporting google oauth

---

pkg/auth/google/auth.go

* Addressed comments from review of #274 
* Made email availability a strict requirement (on scopes): it is provided by default when authenticating
through gcloud, but may be disabled: this should block datamon from proceeding further.

fix(authentication): fixed error message, made email a required scope

---

pkg/auth/google/auth.go
pkg/auth/status/status.go
pkg/errors/errors.go
pkg/errors/errors_test.go

This is an experimental PR attempting to wrap errors in a clean and concise way, 
based on the new go1.13 native error handling.
I am still thinking that the ` fmt.Errorf("%w", err)` hack is untidy...
I applied this to the new `auth` package to illustrate usage. Feedback welcome.

Wrapping errors

---

cmd/metrics/cmd/mock_dest_store.go
pkg/core/bundle_list_test.go
pkg/core/bundle_test.go
pkg/model/bundle.go
pkg/model/bundle_test.go
pkg/model/label.go
pkg/model/repo.go

This is an artifact of initial churn in code. The deserialization should
match the file path.

Fix paths to reflect deserialization choice.

---

pkg/cafs/writer.go

Include the actual key that failed, it is needed to be able to sort
through the service providers logs.

Improve error logging.

---

.golangci.yml
pkg/cafs/cafs.go
pkg/core/bundle.go
pkg/core/bundle_pack.go
pkg/model/bundle.go

Currently there is a single deduplication scheme but we should add
support to list the deduplication scheme in preparation for adding
other schemes.

Add support for capturing the deduplication scheme.

---

.circleci/config.yml

Merging goreleaser PR (#305) did break CI (attempts to release on every master...). Now fixed.

fix(ci): exclude release job from untagged commits

---

cmd/datamon/cmd/config.go
cmd/datamon/cmd/config_generate.go
cmd/datamon/cmd/flags.go
cmd/datamon/cmd/self_upgrade.go
cmd/datamon/cmd/self_upgrade_test.go
docs/usage/datamon.md
docs/usage/datamon_config_create.md
docs/usage/datamon_context_create.md
docs/usage/datamon_context_get.md
pkg/core/bundle_list.go
pkg/core/fs_ro_ops.go
pkg/core/repo_list.go
pkg/core/status/status.go
pkg/errors/errors.go
pkg/errors/errors_test.go
pkg/storage/doc.go
pkg/storage/gcs/errors.go
pkg/storage/gcs/store.go
pkg/storage/localfs/store.go
pkg/storage/multi.go
pkg/storage/status/status.go
pkg/storage/sthree/errors.go
pkg/storage/sthree/store.go
pkg/storage/store.go

* pkg (storage, core): wrap underlying API errors and process well-known error statuses
* CLI: add more detailed guidance on well-known errors (e.g. invalid bucket, unknown context)
**NOTE**: if we all agree on the idea behind this PR (which starts levering my previous error wrapper), I'll start generalizing error wrapping in packages. Step-by-step CLI testing shall also drive toward more "extra guidance"-like handling.

feat: leverages error wrapping

---

cmd/datamon/cmd/flags.go
pkg/context/context.go
pkg/context/context_test.go
pkg/context/gcs/doc.go
pkg/context/gcs/gcs_context.go
pkg/context/status/status.go
pkg/core/bundle.go
pkg/core/bundle_test.go

refact(context): make context an interface
9900184
* transformed Context as an interface, with our default basic implementation kept private
* moved gcs specific section of cmd/flags.go used to initialize context stores on gcs to a helper sub package of context,
which provides a context storage strategy 100% backed by gcs (we might want to create later more elaborate strategies)

refact(context): make context an interface

---

.circleci/config.yml

@kerneltime the release job did not trigger on your latest tagging attempt.
I checked and fixed the CI config which was mixing up filters with branches.
I've launched a dummy circleCI job on my fork and the release job now kicks in.
The way to apply the fix after merger is:
- remove the v2.0.0-beta tag from your local and origin (and basically all remotes you might have)
- retag after this commit
- `git push origin v2.0.0-beta` 
Obviously I cannot run a full fledged CI on my fork, because I am missing the whole circleCI context on my personal circleCI config.

fixup CI vs tags

---

.circleci/config.yml

I've done this dozen of times and every time, I get confused with CircleCI filtering rules.
Hope it's better now, as this run seems to show up as expected: https://app.circleci.com/github/fredbi/datamon/pipelines

fixup CI filters again

---

cmd/datamon/cmd/bundle_get.go
cmd/datamon/cmd/config.go
cmd/datamon/cmd/context_get.go
cmd/datamon/cmd/label_get.go
cmd/datamon/cmd/repo_get.go
pkg/errors/errors.go

Error wrapping did introduce some race conditions by returning the _same_ variable
when wrapping, instead of _a copy_ of the error. This PR fixes the problem.
ATTENTION: this a prerequisite for releasing. PR #339 is based on top of this one.
* fixes #336

fix(errors): fixed race conditions with unduly mutable errors

---

.circleci/config.yml
.goreleaser.yml
cmd/datamon/cmd/self_upgrade.go
cmd/datamon/cmd/self_upgrade_test.go
go.mod
go.sum

> I know this one is quite hard to review because it interacts with many things.
> My apologies for that. It is probably not that easy to release the releaser...
> I've tried to add a much material as I could to get some understanding of what's going on here.
> You may also have a look at some CI pipeline executions (yes, many failed over the past few days...).
- onboards regression fix PR #337 
- fixes CI stuff preventing release (many little things that required some ssh in-container debug)
- temporarily enables releasing from a branch with special name "goreleaser-debug", for debugging purpose
- successfully tested on some dummy prebeta tags (tags and release artifacts since removed)
- verified that the homebrew-datamon repo is properly updated
Additional manual tests (beyond CI):
Now …

Goreleaser debug

---

.golangci.yml
cmd/datamon/cmd/self_upgrade.go
go.mod
go.sum

Reverted from forked dependency back to main repo after maintainer of https://github.com/rhysd/go-github-selfupdate
did kindly merge my fix to support releases with multiple artifacts.

fix(cli): self-update

---

cmd/datamon/cmd/context.go
cmd/datamon/cmd/context_create.go
cmd/datamon/cmd/context_get.go
cmd/datamon/cmd/context_list.go
docs/usage/datamon_context.md
docs/usage/datamon_context_create.md
docs/usage/datamon_context_get.md
docs/usage/datamon_context_list.md
pkg/context/status/status.go
pkg/core/context_list.go
pkg/core/status/status.go
pkg/model/context.go
pkg/model/paths.go

* adds datamon context list command
* revisits remote config metadata structure for contexts, i.e. adds path `contexts/{context}`
* makes context rendering more explicit (template)
* fixes [RES-1438]
The CI ~~does not pass because this PR~~ now passes -- This PR brings a breaking change to the structure of the remote config. If we agree on the principle of this change, I can make it to work by adapting the remote config (simply copying the */context.yaml into contexts/*/context.yaml in the config bucket).
~~For the moment, I am not changing the test remote config that Ransom did create.~~
@ransomw1c I've now adapted the remote config bucket used by the fuse test, but did not remove anything yet: just copied the context.yaml definitions into the new `/contexts/{xxxx}/context.yaml` …

feat: context list CLI

---

cmd/datamon/cmd/bundle_mutable_mount.go

Add ability to assign a label when creating a bundle
via a mutable Fuse mount.

Add label support for mutable FS mount.

---

cmd/datamon/cmd/flags.go
cmd/datamon/cmd/web.go
docs/usage/datamon_bundle_mount_new.md
docs/usage/datamon_web.md
go.mod
go.sum

* changed default port to random, --port can still be used to specify a port
* added no-browser flag, to prevent launching of browser

feat(web): added auto-start with browser on datamon web CLI

---

pkg/core/fs_common.go

fix(core): failed to create backing file now displays as a warning, not an error

---

cmd/datamon/cmd/bundle_mutable_mount.go
pkg/core/fs.go
pkg/core/fs_common.go
pkg/core/fs_integration_test.go
pkg/core/fs_ro_ops.go
pkg/core/fs_rw_ops.go
pkg/core/fs_test.go

fix(core): removed explicit stubbed FS methods and replaced them by imported fuse lib NotImplemented versions
This makes it easier to update the dependency to the fuse package (but we lose the logging of non implemented methods)
* fixes #332
fix(core): factorized type declaration and logging on core FS implementations
Same logging mechanism and interface drives both ro and rw implementations.

coreFS minor enhancements

---

hack/fuse-demo/wrap_application.sh

this is a quick improvement noticed while lining up `wrap_datamon.sh` removal:  `wrap_application.sh` previously assumed `/bin/bash` to be available in an Argo DAG node's main container when using datamon with the pipelines tool.
since the availability of a POSIX standard shell at `/bin/sh` is gauranteed by linux distros and since the `shellcheck` in CI verifies that `wrap_application.sh` is POSIX-compliant, this is a relaxation or usage requirements to support a strictly larger set of uses, not a breaking change.

wrap_application.sh uses POSIX shebang

---

cmd/datamon/cmd/bundle_preserve_disable.go
cmd/datamon/cmd/bundle_preserve_enable.go
cmd/datamon/cmd/bundle_upload.go
pkg/core/bundle.go
pkg/core/bundle_pack.go

This option is interesting to migrate bundles from one store to another while preserving the initial ID.
Preservation allows for migration jobs to be idempotent and to restart on errors.
TODO(fred): tested manually so far, needs some U.T

feat(upload): added option to preserve bundleID on upload

---

pkg/storage/gcs/store.go
pkg/storage/instrumented.go
pkg/storage/localfs/store.go
pkg/storage/multi.go
pkg/storage/store.go
pkg/wal/wal_test.go

Removed aliased type to bool.
Go aliased types (i.e. type A = B) are a syntactic sugar only.
This is different from type redefinitions (i.e. type A B), which create a new type for the compiler.
The original intent was to construct some kind of enumerated type, for a... boolean.
I chose to remove all this and just go back to plain bool.
* contributes #374

chore(storage): smallish refactoring series, part 1

---

.circleci/config.yml
cmd/datamon/cmd/cli_fuse_test.go
cmd/datamon/cmd/cli_test.go
cmd/datamon/cmd/cli_workshop_test.go
cmd/datamon/cmd/config_set.go
cmd/datamon/cmd/flags.go
cmd/datamon/cmd/root.go

This unrolls the workshop entirely, including `brew install datamon` (with `linuxbrew`).
Not covered:
- web browser launch (covered by other tests)
- self upgrade (covered by other tests)
- context creation (covered by other tests)
- RW fuse mount (covered by other tests)
**NOTE on this for the future**: struggled with two pain points I wouldn't have expected at first:
1. non-interactive install of brew on CI has been a pain (trying  many hacks and stuff, eventually it works...)
2. some tests run os.Setenv(), which in turn pollute some other ones depending on the order of execution => need to rethink a bit our common launch pad mockery

test(cli): added CLI test to cover workshop sessions items

---

.circleci/config.yml

**NOTE**: this bends on #381 
Generated artifacts are available at: https://app.circleci.com/jobs/github/oneconcern/datamon/5009/artifacts
Our CI workflows have become complex over time. Time for refactoring a bit.
- machine executor install refactoring
* refactored VM install to clarify the various steps (brew, fuse, golang)
* revisited golang install on VM dedicated to fuse tests: picks latest release automatically
- other jobs factorized with commands
* factorized go module cache handling as shorter commands
* clarified credentials setup with an explicit command
* removed redundant environment specs
- test coverage reporting
* refactored test coverage collection and reporting as CI artifacts, using a trailer job to merge coverage metrics
* kept the junit test report as test_result …

refact(ci): revisited vm install, test coverage

---

cmd/datamon/cmd/bundle.go
cmd/datamon/cmd/bundle_diff.go
cmd/datamon/cmd/bundle_download.go
cmd/datamon/cmd/bundle_download_file.go
cmd/datamon/cmd/bundle_get.go
cmd/datamon/cmd/bundle_list.go
cmd/datamon/cmd/bundle_list_file.go
cmd/datamon/cmd/bundle_mount.go
cmd/datamon/cmd/bundle_mutable_mount.go
cmd/datamon/cmd/bundle_update.go
cmd/datamon/cmd/bundle_upload.go
cmd/datamon/cmd/cli_test.go
cmd/datamon/cmd/config.go
cmd/datamon/cmd/config_set.go
cmd/datamon/cmd/context.go
cmd/datamon/cmd/context_create.go
cmd/datamon/cmd/flags.go
cmd/datamon/cmd/label.go
cmd/datamon/cmd/label_get.go
cmd/datamon/cmd/label_list.go
cmd/datamon/cmd/label_set.go
cmd/datamon/cmd/repo.go
cmd/datamon/cmd/repo_create.go
cmd/datamon/cmd/repo_get.go
cmd/datamon/cmd/repo_list.go
cmd/datamon/cmd/root.go
cmd/datamon/cmd/web.go
pkg/web/packrd/packed-packr.go

these are some cleanup of the `cmd/datamon/cmd/` package.
the create and read tests for `config set` are separated out to #394 .

cmd pkg cleanup

---

cmd/datamon/cmd/cli_fuse_test.go
cmd/datamon/cmd/cli_workshop_test.go

update the `WorkshopTest` to include a smoke test of the `web` command at the same level of abstraction (driving the cli as a binary rather than using Cobra's api) as the remainder of that test.
`routes_test.go` remains the place for more detailed specification- and documentation-by-test of the `web` package.

init workshop web test

---

go.mod
internal/rand/randomdata.go
internal/rand/randomdata_test.go
pkg/cafs/cafs_test.go
pkg/cafs/fake_data_generator.go
pkg/cafs/fake_data_generator_test.go
pkg/cafs/hasher_test.go
pkg/cafs/mocks_test.go
pkg/cafs/reader_test.go

* introduced new, faster, random data generator
* faster cafs tests with faster random generator, less string <-> []byte conversions
NOTE: I am also introducing here the use of "golang.org/x/sync/errgroup", which might help us simplify some of our goroutine patterns in the near future.
NOTE: on CI run, the cafs test suite goes from 42 sec down to 4s. Generalizing the new generator to other consuming packages shall bring testing time further down.

test(cafs): Faster cafs test suite

---

cmd/datamon/cmd/bundle.go
cmd/datamon/cmd/bundle_diff.go
cmd/datamon/cmd/bundle_download.go
cmd/datamon/cmd/bundle_download_file.go
cmd/datamon/cmd/bundle_get.go
cmd/datamon/cmd/bundle_list_file.go
cmd/datamon/cmd/bundle_mount.go
cmd/datamon/cmd/bundle_mutable_mount.go
cmd/datamon/cmd/bundle_update.go
cmd/datamon/cmd/bundle_upload.go
cmd/datamon/cmd/label_get.go
cmd/datamon/cmd/label_set.go
cmd/metrics/cmd/upload.go
pkg/core/bundle.go
pkg/core/bundle_options.go
pkg/core/bundle_test.go
pkg/core/bundle_unpack.go
pkg/core/label.go
pkg/core/label_list.go
pkg/core/label_options.go
pkg/fuse/mocks/fs_test_utils.go
pkg/model/bundle.go
pkg/model/bundle_options.go
pkg/model/label.go
pkg/model/label_options.go
pkg/web/routes.go

* Principle: move constructors and option functors to the package that declares the type
* The main use case for core.NewBundle() being core.NewBundle(core.NewBDescriptor(), replaced
this by default and added an option to override the descriptor.
NOTE: this point has been discussed in one of the diamond PR's (commented by  @ransomw1c ), in which I have anticipated this layout for the new core objects (i.e. establishing a clearer divide between core and model).

refact(model): moved constructors and options for metadata models from core to model

---

.circleci/config.yml

**Description:**
Datamon being an Open Source Project we don’t want any One Concern details revealed to the public anywhere in the code base. And we noticed that on the Circle CI yaml file there are a couple of parameters that are revealed and should not be.
Got rid of:
* Google Project ID
* Cluster Name

feat(ops): [RES-2173] Cleaned up circleci details

---

.circleci/config.yml
cmd/datamon/cmd/cli_workshop_test.go
cmd/datamon/cmd/config_set.go
cmd/datamon/cmd/self_upgrade_test.go
pkg/cafs/reader_test.go
pkg/fuse/mocks/fs_test_utils.go
pkg/sidecar/param/pub_api.go

The linter has changed some defaults regarding false positives with gosec.
* gosec warnings fixed with either reduced privileges (test programs) or //nolint directives (i.e. don't know if relevant to fix)
* changed linting strategy to be based on diff with master and not scanning the whole repo, possibly digging out old things not related to a PR's changes
* added timeout to linter (which defaults to 1m), as circleCI sometimes delivers very scarce resources to our containers

chore(linting): fixed linting after golangci default behavior has changed

---

pkg/storage/localfs/store.go
pkg/storage/localfs/store_test.go

fix(localfs): fixed Put flags: added O_TRUNC (avoids file corruption when updating a file), removed 0600
fix(localfs): implemented KeysPrefix method (cursory implementation, primarily intended to use localfs as a mocked up Store)
fix(localfs): added the WithLock option to guard localfs against concurrent R/W and W/W options
**Motivation:**
I am building up some elaborate testcases for the diamonds feature, based on mocked localfs.
This brought up several issues with concurrent updates and required an implementation of KeysPrefix.
The new KeyPrefix is certainly not very scalable, but at least it
supports my testcases with core. I am not sure there is a better
way to go with afero.

Diamonds #3: fix(localfs)

---

.circleci/config.yml

This PR upgrades the resource class used to run our tests.
The default instance ("medium") is often failing on memory shortage or time outs.
Upgrading to "medium+" beefs up a bit the workflows, at marginal cost in circleci credits.
Testing with "large" instances did not improve things since the next bottleneck is the latency to gcs (this story shall also be told).

Upgrade CI sizing

---

.circleci/config.yml

* Running k8s jobs in parallel (sidecar demo jobs) was fine until I added the IP whitelisting
change to abide by our network access restrictions. This triggers are race condition on these
2 workflows and sometimes, one fail because it cannot access our cluster.

Fix whitelisting IP race conditions

---

.circleci/config.yml
docs/proposals/sidecar-analysis.md
docs/sidecar-design.md
docs/sidecar.md

* rewrote user doc on sidecars, essentially a walk-through the examples
* moved the existing material as "sidecar design", which reflects the current design -- remove pg parts that are no more relevant
* introduced a new "analysis" document (could also have called this "impediments"), preliminary to the forthcoming design proposal -- basically challenging https://oneconcern.atlassian.net/browse/RES-1826
NOTE to reviewers: since this builds up on top of other PR you may see the actual changes
by jumping to that commit https://github.com/oneconcern/datamon/pull/433/commits/e94af91c77817294442c8cfbf34db8b518c46d9f

Doc sidecar

---

.circleci/config.yml
cmd/datamon/cmd/root.go
pkg/metrics/metrics.go
pkg/metrics/options.go

* removed unused minio container from metrics executor
* allowed metrics test to keep mute for the duration of the test
* added support for configurable opencensus reporting period
* added default 30 s timeout on metrics write operations
* added some TLS options for https influxdb backends

fix(metrics): timeout management

---

.circleci/config.yml
cmd/datamon/cmd/diamond_cancel.go
cmd/datamon/cmd/diamond_commit.go
cmd/datamon/cmd/diamond_get.go
cmd/datamon/cmd/diamond_initialize.go
cmd/datamon/cmd/split_add.go
cmd/datamon/cmd/split_get.go
pkg/core/bundle_pack.go
pkg/core/bundle_unpack.go
pkg/core/diamond.go
pkg/core/diamond_commit.go
pkg/core/diamond_ops.go
pkg/core/diamond_options.go
pkg/core/index.go
pkg/core/metrics.go
pkg/core/split.go
pkg/core/split_ops.go
pkg/core/split_options.go

fix(metrics): added metrics for diamonds and splits
Extra fixups:
* completed the replacement of direct stores.VMetadata() specification by the common GetDiamondStore()
* added some missing logger injections in datamon/cmd, which were missing on some new diamond/split commands
* updated generated usage doc
fix(metrics): added metrics for bundle operations: throughput, size and number of files

Fix diamond metrics

---

cmd/datamon/cmd/flags.go
cmd/datamon/cmd/label_get.go
cmd/datamon/cmd/label_list.go
docs/usage/datamon_label_get.md
docs/usage/datamon_label_list.md
pkg/core/keys.go
pkg/core/label.go
pkg/core/label_list.go
pkg/core/label_list_test.go
pkg/core/label_options.go
pkg/core/options.go
pkg/core/status/status.go
pkg/storage/gcs/store.go
pkg/storage/gcs/versions.go
pkg/storage/gcs/versions_test.go
pkg/storage/status/status.go
pkg/storage/store.go

My own take on the versioned labels feature, hopefully with minimal changes to the existing code base.
* This allows a user to find out which bundles a given label was previously assigned
* Requires enabled versioning on vmetadata store
* Only supported with GCS
TODO: unit testing has been overlooked - this feature has only been tested manually

Version support for label get and label list

---

cmd/datamon/cmd/flags.go
cmd/sidecar_param/cmd/flags.go
docs/usage/datamon_bundle_upload.md
docs/usage/datamon_diamond_split_add.md
pkg/core/bundle_pack.go
pkg/storage/gcs/options.go
pkg/storage/gcs/store.go
pkg/storage/gcs/store_test.go

Allow uploading a subset of keys within a GCS bucket instead of the entire bucket contents.
- allow the `--path` option for `upload` to accept a GCS url in the format `gs://bucket/path/to/object/`
- upload all files from bucket that start with the prefix included in the URL path
e.g. `path/to/object/`
- use file names in datamon that are relative to the given prefix
e.g. `gs://bucket/path/to/object/is/here.tgz` -> `is/here.tgz`

feat: bundle upload from gcs bucket path

---

.golangci.yml
cmd/datamon/cmd/bundle_download.go
cmd/datamon/cmd/bundle_mutable_mount.go
cmd/datamon/cmd/bundle_upload.go
cmd/datamon/cmd/flags.go
pkg/cafs/cafs.go
pkg/cafs/cafs_options.go
pkg/cafs/check_blob.go
pkg/cafs/mocks_test.go
pkg/cafs/reader.go
pkg/cafs/writer.go
pkg/cafs/writer_options.go
pkg/core/bundle.go
pkg/core/bundle_options.go
pkg/core/bundle_pack.go
pkg/core/bundle_unpack.go
pkg/storage/gcs/store.go
pkg/storage/localfs/store.go
pkg/storage/sthree/store.go
pkg/storage/store.go

On some rare but not impossible occasion, the written root key for a file may become corrupted.
In that case, if the blob has been written, it would never be overwritten again and it becomes impossible to recover that file, even after several subsequent uploads. What is worse, this situation goes completely undetected, and the corruption occurs silently until we attempt to read the corrupted file.
We think a similar situation may occur on any written blob.
This PR proposes a better handling of this situation, even though it remains impossible to totally guarantee against corruptions.
1. Every time we are about to write a root key blob (for each uploaded file), a checksum check is carried out _before_ we decide to skip the write. If the check is unsuccessful, this means that the existing …

fix: detect and recover from corrupted blobs [HAZ-305]
